name: n_dart
description: A simple cross-platform NodeJS version manager.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.1.2
  http: ^0.13.3
  path: ^1.7.0

dev_dependencies:
  lint: ^1.0.0
